package lib
import (
	// "bytes"
	// "encoding/json"
	// "fmt"

	
	// "io/ioutil"
	// "net/http"
	// "os"
)

// type AutoGenerated struct {
// 	Header struct {
// 		Username string `json:"username"`
// 		Password string `json:"password"`
// 		Token string `json:"token"`
// 	} `json:"header"`
// 	Body struct {
// 		RealTimeRequestType struct {
// 			UnitOfTime int `json:"unitOfTime"`
// 			StartDate string `json:"startDate"`
// 			ReportType int `json:"reportType"`
// 			PerformanceData []string `json:"performanceData"`
// 			EndDate string `json:"endDate"`
// 			LevelOfDetails int `json:"levelOfDetails"`
// 		} `json:"realTimeRequestType"`
// 	} `json:"body"`
// }

// func ( this *AutoGenerated )ToJson( stime, etime string )string{
// 		this.Header.Username = "baidu-五圆之梦A06B19KA04575"
// 		this.Header.Password = "IU52di"
// 		this.Header.Token = "19d9b8e6ef5c8a7d703a45d98401248e"
// 		this.Body.RealTimeRequestType.PerformanceData = append( this.Body.RealTimeRequestType.PerformanceData, "impression" )
// 		[ "impression","click",
//         "cost",
//         "ctr",
//         "cpc",
//         "cpm"]
// 		this.Body.RealTimeRequestType.UnitOfTime = 5
// 		this.Body.RealTimeRequestType.StartDate = stime
// 		this.Body.RealTimeRequestType.EndDate = etime
// 		this.Body.RealTimeRequestType.ReportType = 2
// 		this.Body.RealTimeRequestType.LevelOfDetails = 2
// }

